project:
  type: website
  preview:
    # Change port if it's busy in your system or just remove this line so that It will automatically use any free port
    port: 4200
    browser: true
  pre-render:
    - sh assets/scripts/changelog.sh
    - sh assets/scripts/versions.sh

# These cannot be used as variables. They are reserved for the project configuration.
website:
  title: "Turing.jl"
  site-url: https://turinglang.org
  site-path: "/"
  favicon: "assets/favicon.ico"
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: "assets/images/turing-logo.svg"
    # logo-href: https://turinglang.org/
    background: "#073c44"
    foreground: "#ffffff"
    left:
      - href: https://turinglang.org/docs/tutorials/docs-00-getting-started/
        text: Get Started
      - href: https://turinglang.org/docs/tutorials/00-introduction/
        text: Tutorials
      - href: https://turinglang.org/library/
        text: Library API
      - href: news/
        text: News
      - href: team/
        text: Team
    right: 
      - icon: file-earmark-diff
        menu:
          - text: Changelog
            href: changelog.qmd
          # The versions will be inserted here by the script

          - text: v0.33.0
            href: versions/v0.33.0/
          - text: v0.32.3
            href: versions/v0.32.3/
          - text: v0.32.2
            href: versions/v0.32.2/
          - text: v0.32.1
            href: versions/v0.32.1/
          - text: v0.32.0
            href: versions/v0.32.0/
          - text: v0.31.5
            href: versions/v0.31.5/
          - text: v0.31.4
            href: versions/v0.31.4/
          - text: v0.31.3
            href: versions/v0.31.3/
          - text: v0.31.2
            href: versions/v0.31.2/
          - text: v0.31.1
            href: versions/v0.31.1/
          - text: v0.31.0
            href: versions/v0.31.0/
          - text: v0.30.9
            href: versions/v0.30.9/
          - text: v0.30.8
            href: versions/v0.30.8/
          - text: v0.30.7
            href: versions/v0.30.7/
          - text: v0.30.6
            href: versions/v0.30.6/
          - text: v0.30.5
            href: versions/v0.30.5/
          - text: v0.30.4
            href: versions/v0.30.4/
          - text: v0.30.3
            href: versions/v0.30.3/
          - text: v0.30.2
            href: versions/v0.30.2/
          - text: v0.30.1
            href: versions/v0.30.1/
          - text: v0.30.0
            href: versions/v0.30.0/
          - text: v0.29.3
            href: versions/v0.29.3/
          - text: v0.29.2
            href: versions/v0.29.2/
          - text: v0.29.1
            href: versions/v0.29.1/
          - text: v0.29.0
            href: versions/v0.29.0/
          - text: v0.28.3
            href: versions/v0.28.3/
          - text: v0.28.2
            href: versions/v0.28.2/
          - text: v0.28.1
            href: versions/v0.28.1/
          - text: v0.28.0
            href: versions/v0.28.0/
          - text: v0.27.1
            href: versions/v0.27.1/
          # The versions list ends here
    tools:
      - icon: twitter
        href: https://x.com/TuringLang
        text: Turing Twitter
      - icon: github
        href: https://github.com/TuringLang/Turing.jl
        text: Turing GitHub
  
  page-footer:
    background: "#073c44"
    left: |
      Turing is created by <a href="http://mlg.eng.cam.ac.uk/hong/" target="_blank">Hong Ge</a>, and lovingly maintained by the <a href="https://github.com/TuringLang/Turing.jl/graphs/contributors" target="_blank">core team</a> of volunteers. <br>
      The contents of this website are © 2024 under the terms of the <a href="https://github.com/TuringLang/Turing.jl/blob/master/LICENCE" target="_blank">MIT License</a>. 

    right:
      - icon: twitter
        href: https://x.com/TuringLang
        aria-label: Turing Twitter
      - icon: github
        href: https://github.com/TuringLang/Turing.jl
        aria-label: Turing GitHub

  back-to-top-navigation: true
  repo-url: https://github.com/TuringLang/turinglang.github.io/
  repo-actions: [edit, issue]
  repo-link-target: _blank
  page-navigation: true

format:
  html:
    theme:
      light: cosmo
    css: theming/styles.css
    toc: true
    smooth-scroll: true
    code-overflow: wrap
    output-block-background: true

# Global Variables to use in any qmd files using:
# {{< meta site-url >}}
site-url: https://turinglang.org
get-started: https://turinglang.org/docs/tutorials/docs-00-getting-started/
tutorials-intro: https://turinglang.org/docs/tutorials/00-introduction/
