project:
  type: website
  preview:
    # Change port if it's busy in your system or just remove this line so that It will automatically use any free port
    port: 4200
    browser: true

# These cannot be used as variables. They are reserved for the project configuration.
website:
  title: "Turing.jl"
  site-url: https://turinglang.org
  site-path: "/"
  favicon: "assets/favicon.ico"
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: "assets/images/turing-logo.svg"
    background: "#073c44"
    foreground: "#ffffff"
    left:
      - text: Get Started
        href: https://turinglang.org/docs/tutorials/docs-00-getting-started/
      - text: Tutorials
        href: https://turinglang.org/docs/tutorials/00-introduction/
      - text: Libraries
        href: library/
      - text: News
        href: news/
      - text: Team
        href: team/
    tools:
      - icon: twitter
        text: Turing Twitter
        href: https://x.com/TuringLang
      - icon: github
        text: Turing GitHub
        href: https://github.com/TuringLang/Turing.jl
  
  # page-footer:
  #   background: "#073c44"
  #   left: |
  #     Turing is created by <a href="http://mlg.eng.cam.ac.uk/hong/" target="_blank">Hong Ge</a>, and lovingly maintained by the <a href="https://github.com/TuringLang/Turing.jl/graphs/contributors" target="_blank">core team</a> of volunteers. <br>
  #     The contents of this website are © 2024 under the terms of the <a href="https://github.com/TuringLang/Turing.jl/blob/master/LICENCE" target="_blank">MIT License</a>. 

  #   right:
  #     - icon: twitter
  #       href: https://x.com/TuringLang
  #       aria-label: Turing Twitter
  #     - icon: github
  #       href: https://github.com/TuringLang/Turing.jl
  #       aria-label: Turing GitHub
  #     - icon: discourse
  #       href: https://github.com/TuringLang/Turing.jl

  back-to-top-navigation: true
  repo-url: https://github.com/TuringLang/turinglang.github.io/
  page-navigation: true

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theming/theme-dark.scss]
    css: theming/styles.css
    toc: false
    sidebar: false
    smooth-scroll: true
    code-overflow: wrap
    output-block-background: true
    include-after-body:
      text: |
        <footer id="footer">
          <style>#footer p{text-align: center !important;}</style>
          <p>Turing is created by <a href="http://mlg.eng.cam.ac.uk/hong/" target="_blank">Hong Ge</a>, and lovingly maintained by the <a href="https://github.com/TuringLang/Turing.jl/graphs/contributors" target="_blank">core team</a> of volunteers.</p>
          <p>Follow us on <a href="https://x.com/TuringLang" class="twitter-link"><span class="footer-icon footer-twitter-icon"></span>@TuringLang</a> and check out our GitHub <a href="https://github.com/TuringLang/" class="github-link"><span class="footer-icon footer-github-icon"></span>TuringLang</a>.</p>
          <p>&copy; 2024 under the terms of the <a href="https://github.com/TuringLang/Turing.jl/blob/master/LICENCE" target="_blank">MIT License</a>.</p>
        </footer>

# Global Variables to use in any qmd files using:
# {{< meta site-url >}}
site-url: https://turinglang.org
get-started: https://turinglang.org/docs/tutorials/docs-00-getting-started/
tutorials-intro: https://turinglang.org/docs/tutorials/00-introduction/
